# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/islem.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class IslemWindowUI(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(204, 86)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 204, 26))
        self.menubar.setObjectName("menubar")
        self.menu_lem = QtWidgets.QMenu(self.menubar)
        self.menu_lem.setObjectName("menu_lem")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionYeni_Soru = QtWidgets.QAction(MainWindow)
        self.actionYeni_Soru.setObjectName("actionYeni_Soru")
        self.actionSoru_Sec = QtWidgets.QAction(MainWindow)
        self.actionSoru_Sec.setObjectName("actionSoru_Sec")
        self.menu_lem.addAction(self.actionYeni_Soru)
        self.menu_lem.addAction(self.actionSoru_Sec)
        self.menubar.addAction(self.menu_lem.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.menu_lem.setTitle(_translate("MainWindow", "İşlem"))
        self.actionYeni_Soru.setText(_translate("MainWindow", "Yeni Soru EKle "))
        self.actionSoru_Sec.setText(_translate("MainWindow", "Soru Sec"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = IslemWindowUI()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
